title: "P-SSCRM: Proactive Secure Software Supply Chain Risk Management"
description: "P-SSCRM is a framework for managing software supply chain security risk."
baseurl: ""
url: ""

collections:
  groups:
    output: false
  practices:
    output: false
  controls:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

participate_form_url: "#"

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - docs
  - DEVELOPMENT.md
  - README.md
  - node_modules
