#!/usr/bin/env python3
"""Regenerate _groups, _practices, _controls, and the data files under _data/
from the P-SSCRM source-of-truth data.

Sources:
  - https://github.com/p-sscrm/p-sscrm            (framework definition)
  - https://github.com/p-sscrm/ats-to-ts           (MITRE ATT&CK mapping)

This script OVERWRITES every file in _groups, _practices, _controls, and
every file listed above under _data/. Do not hand-edit files in those
locations — edit the upstream repos instead and re-run this script.

Usage: python3 scripts/sync_data.py
"""
import json
import re
import urllib.request
from pathlib import Path

DATA_LISTING_URL = "https://api.github.com/repos/p-sscrm/p-sscrm/contents/data"
MITRE_DATA_LISTING_URL = "https://api.github.com/repos/p-sscrm/ats-to-ts/contents/data"
MITRE_RAW_BASE = "https://raw.githubusercontent.com/p-sscrm/ats-to-ts/main/data"

VERSION_FILE_RE = re.compile(r"^p-sscrm-(\d+)_(\d+)\.json$")
MITRE_VERSION_DIR_RE = re.compile(r"^v(\d+)\.(\d+)$")

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "_data"

GENERATED_NOTICE = "# Auto-generated by scripts/sync_data.py from p-sscrm/p-sscrm — do not edit by hand."


def fetch_json(url):
    with urllib.request.urlopen(url) as resp:
        return json.load(resp)


def slug(code):
    """'G.1.1' -> 'g-1-1', 'G' -> 'g'"""
    return code.lower().replace(".", "-")


def source_key(source_id):
    """'SSDF AI' -> 'ssdf-ai', '800-161' -> '800-161'"""
    return source_id.lower().replace(" ", "-")


def yaml_str(value):
    return json.dumps(value, ensure_ascii=False)


def write_front_matter(path, fields, body):
    lines = ["---", GENERATED_NOTICE]
    for key, value in fields:
        lines.append(format_field(key, value))
    lines.append("---")
    lines.append("")
    lines.append(body.strip())
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def format_field(key, value, indent=""):
    if isinstance(value, dict):
        out = [f"{indent}{key}:"]
        for k, v in value.items():
            out.append(f"{indent}  {yaml_str(k)}: {yaml_str(v)}")
        return "\n".join(out)
    if isinstance(value, list):
        if not value:
            return f"{indent}{key}: []"
        out = [f"{indent}{key}:"]
        for item in value:
            out.append(f"{indent}  - {yaml_str(item)}")
        return "\n".join(out)
    if isinstance(value, bool):
        return f"{indent}{key}: {'true' if value else 'false'}"
    if isinstance(value, int):
        return f"{indent}{key}: {value}"
    return f"{indent}{key}: {yaml_str(value)}"


def clear_generated_dirs():
    for name in ("_groups", "_practices", "_controls"):
        d = ROOT / name
        d.mkdir(parents=True, exist_ok=True)
        for f in d.glob("*.md"):
            f.unlink()


def write_frameworks_data(metadata):
    lines = [
        "# Auto-generated by scripts/sync_data.py from p-sscrm/p-sscrm — do not edit by hand.",
        "",
    ]
    for entry in metadata:
        key = source_key(entry["id"])
        display_name = entry["id"].replace(" ", "-")
        lines.append(f"{yaml_str(key)}:")
        lines.append(f"  name: {yaml_str(display_name)}")
        lines.append(f"  full_name: {yaml_str(entry['title'])}")
        lines.append(f"  url: {yaml_str(entry['link'])}")
        lines.append("")
    (DATA / "frameworks.yaml").write_text("\n".join(lines), encoding="utf-8")


def find_versions():
    """Look at the data/ directory of p-sscrm/p-sscrm on GitHub and return
    every p-sscrm-X_Y.json file found, sorted newest first."""
    listing = fetch_json(DATA_LISTING_URL)
    versions = []
    for entry in listing:
        match = VERSION_FILE_RE.match(entry["name"])
        if not match:
            continue
        major, minor = (int(match.group(1)), int(match.group(2)))
        versions.append(
            {
                "version": f"{major}.{minor}",
                "sort_key": (major, minor),
                "download_url": entry["download_url"],
            }
        )
    versions.sort(key=lambda v: v["sort_key"], reverse=True)
    return versions


def write_versions_data(versions):
    lines = [
        "# Auto-generated by scripts/sync_data.py from p-sscrm/p-sscrm — do not edit by hand.",
        "",
    ]
    for i, v in enumerate(versions):
        lines.append("- version: " + yaml_str(v["version"]))
        lines.append(f"  current: {'true' if i == 0 else 'false'}")
        lines.append("  download_url: " + yaml_str(v["download_url"]))
    (DATA / "versions.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def find_mitre_versions():
    """Look at the data/ directory of p-sscrm/ats-to-ts on GitHub and return
    every vX.Y version directory found, sorted newest first."""
    listing = fetch_json(MITRE_DATA_LISTING_URL)
    versions = []
    for entry in listing:
        if entry["type"] != "dir":
            continue
        match = MITRE_VERSION_DIR_RE.match(entry["name"])
        if not match:
            continue
        major, minor = (int(match.group(1)), int(match.group(2)))
        versions.append(
            {
                "version": f"{major}.{minor}",
                "sort_key": (major, minor),
                "download_url": f"{MITRE_RAW_BASE}/{entry['name']}/simple/mappings.json",
            }
        )
    versions.sort(key=lambda v: v["sort_key"], reverse=True)
    return versions


def write_mitre_versions_data(versions):
    lines = [
        "# Auto-generated by scripts/sync_data.py from p-sscrm/ats-to-ts — do not edit by hand.",
        "",
    ]
    for i, v in enumerate(versions):
        lines.append("- version: " + yaml_str(v["version"]))
        lines.append(f"  current: {'true' if i == 0 else 'false'}")
        lines.append("  download_url: " + yaml_str(v["download_url"]))
    (DATA / "mitre_versions.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_mitre_index(mapping_rows):
    index = {}
    for row in mapping_rows:
        task_id = row["P-SSCRM Task"]
        index.setdefault(task_id, []).append(row["MITRE ATTACK Technique"])
    for task_id in index:
        index[task_id].sort()
    return index


def main():
    print(f"Fetching {DATA_LISTING_URL}")
    versions = find_versions()
    if not versions:
        raise SystemExit("No p-sscrm-X_Y.json files found in p-sscrm/p-sscrm data/")
    current_url = versions[0]["download_url"]

    print(f"Fetching {current_url}")
    framework = fetch_json(current_url)

    print(f"Fetching {MITRE_DATA_LISTING_URL}")
    mitre_versions = find_mitre_versions()
    if not mitre_versions:
        raise SystemExit("No vX.Y directories found in p-sscrm/ats-to-ts data/")
    mitre_current_url = mitre_versions[0]["download_url"]

    print(f"Fetching {mitre_current_url}")
    mitre_rows = fetch_json(mitre_current_url)
    mitre_index = build_mitre_index(mitre_rows)

    DATA.mkdir(parents=True, exist_ok=True)
    clear_generated_dirs()
    write_frameworks_data(framework["metadata"])
    write_versions_data(versions)
    write_mitre_versions_data(mitre_versions)

    group_count = practice_count = task_count = 0

    for gi, group in enumerate(framework["groups"], start=1):
        group_slug = slug(group["id"])
        write_front_matter(
            ROOT / "_groups" / f"{group_slug}.md",
            [
                ("title", group["name"]),
                ("code", group["id"]),
                ("slug", group_slug),
                ("weight", gi * 10),
            ],
            group["description"],
        )
        group_count += 1

        for pi, practice in enumerate(group["practices"], start=1):
            practice_slug = slug(practice["id"])
            write_front_matter(
                ROOT / "_practices" / f"{practice_slug}.md",
                [
                    ("title", practice["name"]),
                    ("code", practice["id"]),
                    ("slug", practice_slug),
                    ("group", group_slug),
                    ("weight", pi * 10),
                ],
                practice["description"],
            )
            practice_count += 1

            for ti, task in enumerate(practice["tasks"], start=1):
                task_slug = slug(task["id"])
                frameworks = {}
                for ref in task.get("references", []):
                    frameworks[source_key(ref["source"])] = ", ".join(ref["sections"])
                mitre = mitre_index.get(task["id"], [])

                fields = [
                    ("title", task["name"]),
                    ("code", task["id"]),
                    ("slug", task_slug),
                    ("practice", practice_slug),
                    ("weight", ti * 10),
                    ("frameworks", frameworks),
                ]
                if mitre:
                    fields.append(("mitre_attack", mitre))

                write_front_matter(
                    ROOT / "_controls" / f"{task_slug}.md",
                    fields,
                    task["objective"],
                )
                task_count += 1

    print(f"Wrote {group_count} groups, {practice_count} practices, {task_count} controls.")


if __name__ == "__main__":
    main()
